let charactersData = [{
        id: 1,
        name: "Anna",
        hp: 40,
        defense: 5,
        attack: 15,
        image: 'anna.png',
        fandom: "Frozen",
        category: ["Movies","Disney"],
        inParty: 0,
        dead: false
      },
      {
        id: 2,
        name: "Aragorn",
        hp: 100,
        defense: 10,
        attack: 30,
        image: 'aragorn.png',
        fandom: "Lord of the Rings",
        category: ["Movies","Books"],
        inParty: 0,
        dead: false
      },
      {
        id: 3,
        name: "Arthas",
        hp: 100,
        defense: 10,
        attack: 30,
        image: 'arthas.jpg',
        fandom: "World of Warcraft",
        category: ["Video Games","Villains"],
        inParty: 0,
        dead: false
      },
      {
        id: 4,
        name: "Ashitaka",
        hp: 60,
        defense: 6,
        attack: 25,
        image: 'ashitaka.jpg',
        fandom: "Princess Mononoke",
        category: ["Movies","Anime","Protagonists","Disney"],
        inParty: 0,
        dead: false
      },
      {
        id: 5,
        name: "Astrid",
        hp: 80,
        defense: 8,
        attack: 25,
        image: 'astrid.jpg',
        fandom: "How To Train Your Dragon",
        category: ["Movies","Dreamworks"],
        inParty: 0,
        dead: false
      },
      {
        id: 6,
        name: "Baine",
        hp: 90,
        defense: 10,
        attack: 25,
        image: 'baine.jpg',
        fandom: "World of Warcraft",
        category: ["Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 7,
        name: "Batman",
        hp: 70,
        defense: 10,
        attack: 30,
        image: 'batman.png',
        fandom: "Batman",
        category: ["Movies","Video Games","TV Series","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 8,
        name: "Baymax",
        hp: 100,
        defense: 10,
        attack: 15,
        image: 'baymax.jpg',
        fandom: "Big Hero 6",
        category: ["Movies","Disney"],
        inParty: 0,
        dead: false
      },
      {
        id: 9,
        name: "Bilbo Baggins",
        hp: 50,
        defense: 5,
        attack: 25,
        image: 'bilbo.png',
        fandom: "Lord of the Rings",
        category: ["Books","Movies","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 10,
        name: "Buggy",
        hp: 60,
        defense: 5,
        attack: 25,
        image: 'buggy.png',
        fandom: "One Piece",
        category: ["Villains","Anime","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 11,
        name: "Bulbasaur",
        hp: 80,
        defense: 8,
        attack: 20,
        image: 'bulbasaur.jpg',
        fandom: "Pokemon",
        category: ["Movies","Anime","Video Games","TV Series","Pokemon"],
        inParty: 0,
        dead: false
      },
      {
        id: 12,
        name: "Charmander",
        hp: 70,
        defense: 6,
        attack: 25,
        image: 'charmander.jpg',
        fandom: "Pokemon",
        category: ["Movies","Anime","Video Games","TV Series","Pokemon"],
        inParty: 0,
        dead: false
      },
      {
        id: 13,
        name: "Chihiro",
        hp: 40,
        defense: 4,
        attack: 15,
        image: 'chihiro.jpg',
        fandom: "Spirited Away",
        category: ["Movies","Disney","Anime","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 14,
        name: "Cloud",
        hp: 70,
        defense: 6,
        attack: 30,
        image: 'cloud.png',
        fandom: "Final Fantasy",
        category: ["Movies","Video Games","Anime","Protagonists"],
        inParty: 0,
        dead: false
      },      {
        id: 15,
        name: "Daenerys",
        hp: 50,
        defense: 5,
        attack: 25,
        image: 'daenerys.jpg',
        fandom: "Game of Thrones",
        category: ["TV Series","Books"],
        inParty: 0,
        dead: false
      },
      {
        id: 16,
        name: "Dragonite",
        hp: 100,
        defense: 7,
        attack: 30,
        image: 'dragonite.png',
        fandom: "Pokemon",
        category: ["Movies","Anime","Video Games","TV Series","Pokemon"],
        inParty: 0,
        dead: false
      },
      {
        id: 17,
        name: "Dumbledore",
        hp: 60,
        defense: 5,
        attack: 30,
        image: 'dumbledore.jpg',
        fandom: "Harry Potter",
        category: ["Movies","Books"],
        inParty: 0,
        dead: false
      },
      {
        id: 18,
        name: "Eevee",
        hp: 70,
        defense: 3,
        attack: 25,
        image: 'eevee.png',
        fandom: "Pokemon",
        category: ["Movies","Anime","Video Games","TV Series","Pokemon"],
        inParty: 0,
        dead: false
      },
      {
        id: 19,
        name: "Elsa",
        hp: 60,
        defense: 6,
        attack: 25,
        image: 'elsa.jpg',
        fandom: "Frozen",
        category: ["Movies","Disney","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 20,
        name: "Erza",
        hp: 100,
        defense: 10,
        attack: 25,
        image: 'erza.png',
        fandom: "Fairy Tail",
        category: ["Anime","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 21,
        name: "Espeon",
        hp: 50,
        defense: 5,
        attack: 30,
        image: 'espeon.jpg',
        fandom: "Pokemon",
        category: ["Movies","Anime","Video Games","TV Series","Pokemon"],
        inParty: 0,
        dead: false
      },
      {
        id: 22,
        name: "Flareon",
        hp: 80,
        defense: 10,
        attack: 20,
        image: 'flareon.jpg',
        fandom: "Pokemon",
        category: ["Movies","Anime","Video Games","TV Series","Pokemon"],
        inParty: 0,
        dead: false
      },
      {
        id: 23,
        name: "Flynn Rider",
        hp: 50,
        defense: 5,
        attack: 20,
        image: 'flynn.png',
        fandom: "Tangled",
        category: ["Movies","Disney","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 24,
        name: "Gandalf",
        hp: 70,
        defense: 5,
        attack: 25,
        image: 'gandalf-1.png',
        fandom: "Lord of the Rings",
        category: ["Movies","Books"],
        inParty: 0,
        dead: false
      },
      {
        id: 25,
        name: "Gardevoir",
        hp: 60,
        defense: 5,
        attack: 30,
        image: 'gardevoir.png',
        fandom: "Pokemon",
        category: ["Movies","Anime","Video Games","TV Series","Pokemon"],
        inParty: 0,
        dead: false
      },
      {
        id: 26,
        name: "Gimli",
        hp: 80,
        defense: 9,
        attack: 22,
        image: 'gimli.png',
        fandom: "Lord of the Rings",
        category: ["Movies","Books"],
        inParty: 0,
        dead: false
      },
      {
        id: 27,
        name: "Grey",
        hp: 70,
        defense: 8,
        attack: 27,
        image: 'grey.png',
        fandom: "Fairy Tail",
        category: ["TV Series","Anime"],
        inParty: 0,
        dead: false
      },
      {
        id: 28,
        name: "Haku",
        hp: 80,
        defense: 7,
        attack: 22,
        image: 'haku-1.jpg',
        fandom: "Spirited Away",
        category: ["Movies","Disney","Anime"],
        inParty: 0,
        dead: false
      },
      {
        id: 29,
        name: "Harry Potter",
        hp: 50,
        defense: 6,
        attack: 24,
        image: 'harryPotter.png',
        fandom: "Harry Potter",
        category: ["Movies","Books","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 30,
        name: "Hermione",
        hp: 50,
        defense: 7,
        attack: 23,
        image: 'hermione.jpg',
        fandom: "Harry Potter",
        category: ["Movies","Books"],
        inParty: 0,
        dead: false
      },
      {
        id: 31,
        name: "Hiccup",
        hp: 60,
        defense: 7,
        attack: 26,
        image: 'hiccup.png',
        fandom: "How to Train Your Dragon",
        category: ["Movies","Dreamworks"],
        inParty: 0,
        dead: false
      },
      {
        id: 32,
        name: "Howl",
        hp: 60,
        defense: 7,
        attack: 28,
        image: 'howl.png',
        fandom: "Howl's Moving Castle",
        category: ["Movies","Disney","Anime"],
        inParty: 0,
        dead: false
      },
      {
        id: 33,
        name: "Ichigo",
        hp: 75,
        defense: 6,
        attack: 30,
        image: 'ichigo.jpg',
        fandom: "Bleach",
        category: ["TV Series","Anime","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 34,
        name: "Illidan",
        hp: 100,
        defense: 7,
        attack: 30,
        image: 'illidan.jpg',
        fandom: "World of Warcraft",
        category: ["Video Games","Villains"],
        inParty: 0,
        dead: false
      },
      {
        id: 35,
        name: "Jaina",
        hp: 80,
        defense: 6,
        attack: 30,
        image: 'jaina.png',
        fandom: "World of Warcraft",
        category: ["Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 36,
        name: "Joker",
        hp: 70,
        defense: 8,
        attack: 25,
        image: 'joker.jpg',
        fandom: "Batman",
        category: ["Movies","Video Games","TV Series","Villains"],
        inParty: 0,
        dead: false
      },
      {
        id: 37,
        name: "Joker",
        hp: 70,
        defense: 6,
        attack: 26,
        image: 'jokerPersona.jpg',
        fandom: "Persona 5",
        category: ["Video Games","Anime","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 38,
        name: "Jolteon",
        hp: 65,
        defense: 6,
        attack: 28,
        image: 'jolteon.jpg',
        fandom: "Pokemon",
        category: ["Movies","Anime","Video Games","TV Series","Pokemon"],
        inParty: 0,
        dead: false
      },
      {
        id: 39,
        name: "Jon Snow",
        hp: 85,
        defense: 6,
        attack: 22,
        image: 'jonSnow.png',
        fandom: "Game of Thrones",
        category: ["TV Series","Books","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 40,
        name: "Kiki",
        hp: 40,
        defense: 5,
        attack: 19,
        image: 'kiki.jpg',
        fandom: "Kiki's Delivery Service",
        category: ["Movies","Anime","Disney","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 41,
        name: "Kristoff",
        hp: 65,
        defense: 8,
        attack: 20,
        image: 'kristoff.jpg',
        fandom: "Frozen",
        category: ["Movies","Disney"],
        inParty: 0,
        dead: false
      },
      {
        id: 42,
        name: "Kvothe",
        hp: 80,
        defense: 6,
        attack: 32,
        image: 'kvothe.jpg',
        fandom: "Kingkiller Chronicles",
        category: ["Books","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 43,
        name: "Legolas",
        hp: 75,
        defense: 6,
        attack: 28,
        image: 'legolas.png',
        fandom: "Lord of the Rings",
        category: ["Books","Movies"],
        inParty: 0,
        dead: false
      },
      {
        id: 44,
        name: "Link",
        hp: 70,
        defense: 8,
        attack: 25,
        image: 'link.jpg',
        fandom: "Zelda",
        category: ["Video Games","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 45,
        name: "Lucy",
        hp: 60,
        defense: 10,
        attack: 25,
        image: 'lucy.png',
        fandom: "Fairy Tail",
        category: ["Anime","TV Series","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 46,
        name: "Luffy",
        hp: 100,
        defense: 10,
        attack: 31,
        image: 'luffy.jpg',
        fandom: "One Piece",
        category: ["Anime","TV Series","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 47,
        name: "Malfurion",
        hp: 100,
        defense: 8,
        attack: 25,
        image: 'malfurion.png',
        fandom: "World of Warcraft",
        category: ["Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 48,
        name: "Margaery",
        hp: 40,
        defense: 6,
        attack: 18,
        image: 'margaery.jpg',
        fandom: "Game of Thrones",
        category: ["TV Series","Books"],
        inParty: 0,
        dead: false
      },
      {
        id: 49,
        name: "Megamind",
        hp: 60,
        defense: 7,
        attack: 25,
        image: 'megamind.png',
        fandom: "Megamind",
        category: ["Movies","Dreamworks","Villains"],
        inParty: 0,
        dead: false
      },
      {
        id: 50,
        name: "Merida",
        hp: 70,
        defense: 7,
        attack: 27,
        image: 'merida.png',
        fandom: "Brave",
        category: ["Movies","Disney","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 51,
        name: "Mononoke",
        hp: 75,
        defense: 8,
        attack: 28,
        image: 'mononoke.jpg',
        fandom: "Princess Mononoke",
        category: ["Movies","Disney","Anime","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 52,
        name: "Mulan",
        hp: 60,
        defense: 9,
        attack: 22,
        image: 'mulan.png',
        fandom: "Mulan",
        category: ["Movies","Disney","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 53,
        name: "Nami",
        hp: 65,
        defense: 10,
        attack: 25,
        image: 'nami.jpg',
        fandom: "One Piece",
        category: ["Anime","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 54,
        name: "Naruto",
        hp: 100,
        defense: 10,
        attack: 30,
        image: 'naruto.png',
        fandom: "Naruto",
        category: ["Anime","TV Series","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 55,
        name: "Natsu",
        hp: 100,
        defense: 10,
        attack: 30,
        image: 'natsu.jpg',
        fandom: "Fairy Tail",
        category: ["Anime","TV Series","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 56,
        name: "Newt",
        hp: 65,
        defense: 9,
        attack: 22,
        image: 'newt.jpg',
        fandom: "Harry Potter",
        category: ["Movies","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 57,
        name: "Night King",
        hp: 100,
        defense: 10,
        attack: 22,
        image: 'nightKing.jpg',
        fandom: "Game of Thrones",
        category: ["TV Series","Books","Villains"],
        inParty: 0,
        dead: false
      },
      {
        id: 58,
        name: "Oddish",
        hp: 65,
        defense: 6,
        attack: 20,
        image: 'oddish.jpg',
        fandom: "Pokemon",
        category: ["TV Series","Movies","Pokemon","Anime","Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 59,
        name: "Olaf",
        hp: 40,
        defense: 4,
        attack: 12,
        image: 'olaf.png',
        fandom: "Frozen",
        category: ["Movies","Disney"],
        inParty: 0,
        dead: false
      },
      {
        id: 60,
        name: "Pikachu",
        hp: 55,
        defense: 6,
        attack: 22,
        image: 'pikachu.png',
        fandom: "Pokemon",
        category: ["TV Series","Movies","Pokemon","Anime","Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 61,
        name: "Quagsire",
        hp: 75,
        defense: 8,
        attack: 23,
        image: 'quagsire.png',
        fandom: "Pokemon",
        category: ["TV Series","Movies","Pokemon","Anime","Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 62,
        name: "Quilava",
        hp: 70,
        defense: 6,
        attack: 26,
        image: 'quilava.png',
        fandom: "Pokemon",
        category: ["TV Series","Movies","Pokemon","Anime","Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 63,
        name: "Rapunzel",
        hp: 50,
        defense: 6,
        attack: 26,
        image: 'rapunzel.jpg',
        fandom: "Tangled",
        category: ["Movies","Disney","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 64,
        name: "Rem",
        hp: 65,
        defense: 9,
        attack: 25,
        image: 'rem.jpg',
        fandom: "RE: Zero",
        category: ["Anime","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 65,
        name: "Renji",
        hp: 75,
        defense: 7,
        attack: 27,
        image: 'renji.jpg',
        fandom: "Bleach",
        category: ["Anime","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 66,
        name: "Robin",
        hp: 70,
        defense: 10,
        attack: 23,
        image: 'robin.png',
        fandom: "One Piece",
        category: ["Anime","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 67,
        name: "Rogue",
        hp: 95,
        defense: 9,
        attack: 28,
        image: 'rogue.png',
        fandom: "Fairy Tail",
        category: ["Anime","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 68,
        name: "Rukia",
        hp: 60,
        defense: 8,
        attack: 24,
        image: 'rukia.jpg',
        fandom: "Bleach",
        category: ["Anime","TV Series","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 69,
        name: "Sabrina",
        hp: 50,
        defense: 7,
        attack: 22,
        image: 'sabrina.png',
        fandom: "Sabrina the Teenage Witch",
        category: ["TV Series","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 70,
        name: "Sakura",
        hp: 70,
        defense: 9,
        attack: 26,
        image: 'sakura.png',
        fandom: "Naruto",
        category: ["TV Series","Anime"],
        inParty: 0,
        dead: false
      },
      {
        id: 71,
        name: "Sanji",
        hp: 80,
        defense: 8,
        attack: 28,
        image: 'sanji.jpg',
        fandom: "One Piece",
        category: ["TV Series","Anime"],
        inParty: 0,
        dead: false
      },
      {
        id: 72,
        name: "Sasuke",
        hp: 85,
        defense: 10,
        attack: 27,
        image: 'sasuke.jpg',
        fandom: "Naruto",
        category: ["TV Series","Anime","Villains"],
        inParty: 0,
        dead: false
      },
      {
        id: 73,
        name: "Sophie",
        hp: 40,
        defense: 4,
        attack: 15,
        image: 'sophie.png',
        fandom: "Howl's Moving Castle",
        category: ["Movies","Disney","Anime","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 74,
        name: "Squirtle",
        hp: 60,
        defense: 8,
        attack: 24,
        image: 'squirtle.png',
        fandom: "Pokemon",
        category: ["TV Series","Movies","Pokemon","Anime","Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 75,
        name: "Sting",
        hp: 90,
        defense: 8,
        attack: 28,
        image: 'sting.png',
        fandom: "Fairy Tail",
        category: ["TV Series","Anime"],
        inParty: 0,
        dead: false
      },
      {
        id: 76,
        name: "Subaru",
        hp: 100,
        defense: 5,
        attack: 18,
        image: 'subaru.jpg',
        fandom: "RE: Zero",
        category: ["TV Series","Anime","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 77,
        name: "Sven",
        hp: 60,
        defense: 5,
        attack: 20,
        image: 'sven.jpg',
        fandom: "Frozen",
        category: ["Movies","Disney"],
        inParty: 0,
        dead: false
      },
      {
        id: 78,
        name: "Sylvanas",
        hp: 100,
        defense: 7,
        attack: 29,
        image: 'sylvanas.png',
        fandom: "World of Warcraft",
        category: ["Video Games","Villains"],
        inParty: 0,
        dead: false
      },
      {
        id: 79,
        name: "Talanji",
        hp: 80,
        defense: 10,
        attack: 23,
        image: 'talanji.jpg',
        fandom: "World of Warcraft",
        category: ["Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 80,
        name: "Tifa",
        hp: 70,
        defense: 8,
        attack: 28,
        image: 'tifa.png',
        fandom: "Final Fantasy",
        category: ["Video Games","Anime","Movies"],
        inParty: 0,
        dead: false
      },
      {
        id: 81,
        name: "Toothless",
        hp: 80,
        defense: 9,
        attack: 31,
        image: 'toothless.jpg',
        fandom: "How to Train Your Dragon",
        category: ["Movies","Dreamworks"],
        inParty: 0,
        dead: false
      },
      {
        id: 82,
        name: "Tyrande",
        hp: 95,
        defense: 9,
        attack: 26,
        image: 'tyrande.jpg',
        fandom: "World of Warcraft",
        category: ["Video Games"],
        inParty: 0,
        dead: false
      },
      {
        id: 83,
        name: "Tyranitar",
        hp: 90,
        defense: 10,
        attack: 26,
        image: 'tyranitar.jpg',
        fandom: "Pokemon",
        category: ["Video Games","Movies","Anime","Pokemon","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 84,
        name: "Tyrion",
        hp: 40,
        defense: 7,
        attack: 19,
        image: 'tyrion.jpg',
        fandom: "Game of Thrones",
        category: ["TV Series","Books"],
        inParty: 0,
        dead: false
      },
      {
        id: 85,
        name: "Umbreon",
        hp: 100,
        defense: 8,
        attack: 24,
        image: 'umbreon.png',
        fandom: "Pokemon",
        category: ["Video Games","Movies","Anime","Pokemon","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 86,
        name: "Usopp",
        hp: 70,
        defense: 7,
        attack: 27,
        image: 'usopp.png',
        fandom: "One Piece",
        category: ["TV Series","Anime"],
        inParty: 0,
        dead: false
      },
      {
        id: 87,
        name: "Vaporeon",
        hp: 90,
        defense: 7,
        attack: 25,
        image: 'vaporeon.png',
        fandom: "Pokemon",
        category: ["Video Games","Movies","Anime","Pokemon","TV Series"],
        inParty: 0,
        dead: false
      },
      {
        id: 88,
        name: "Voldemort",
        hp: 75,
        defense: 6,
        attack: 30,
        image: 'voldemort.png',
        fandom: "Harry Potter",
        category: ["Movies","Books","Villains"],
        inParty: 0,
        dead: false
      },
      {
        id: 89,
        name: "Zelda",
        hp: 75,
        defense: 6,
        attack: 28,
        image: 'zelda.jpg',
        fandom: "Zelda",
        category: ["Video Games","Protagonists"],
        inParty: 0,
        dead: false
      },
      {
        id: 90,
        name: "Zeref",
        hp: 100,
        defense: 10,
        attack: 30,
        image: 'zeref.png',
        fandom: "Fairy Tail",
        category: ["Anime","TV Series","Villains"],
        inParty: 0,
        dead: false
      },
      {
        id: 91,
        name: "Zoro",
        hp: 100,
        defense: 8,
        attack: 30,
        image: 'zoro.jpg',
        fandom: "One Piece",
        category: ["Anime","TV Series"],
        inParty: 0,
        dead: false
      },
    ]
    
export default charactersData;